### PR TITLE
User should be able to update a product 

### PR DESCRIPTION
**Pull request by kimberly-bird**
## Link to Ticket
#8  User should be able to update a product 

## Description of Proposed Changes
- User should be able to update each of the product properties, one at a time. There are 4 tests for this PR: Update product name, description, price, quantity

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout kb_updateProduct
..
cd bangazon-cli.Tests/
dotnet restore
dotnet test

```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* ProductManager.cs
* ProductManager_Should.cs

## Mentions @username

Tag users that need to review this code

## Definition of Done

1. The project must be fully documented. This includes the following:
    1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    1. Every class must be documented with purpose, author, and methods.
    1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each.

### CODE REVIEW

**Comment by krysmathis** [comment]
In ProductManager_Should tests, remove the code which returns the full list in the tests that update the product.

**Comment by kimberly-bird** [comment]
@krysmathis - code that returned full list of product have been removed from tests

**Comment by krysmathis** [comment]
👍

**Comment by Chewieez** [comment]
👍

**Pull request merged**
