### PR TITLE
overload get product with customer id

### PR DESCRIPTION
**Pull request by kimberly-bird**
## Link to Ticket
#4 User add a product to a customer

## Description of Proposed Changes

- Created overloaded method with get all products with customer id as parameter.

## Steps to Test

Outline the steps to test

From root directory: 
```sh
git fetch --all
git checkout kb-make-overload-for-product
cd bangazon-cli.Tests
dotnet restore
dotnet test

```

If that doesn't work, try deleting your bangazon-cli-test.db file and testing again.

If that doesn't work, try deleting both db files. Then: 
```sh
cd bangazon-cli
dotnet run
cd banazon-cli.Tests
dotnet test

```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* ProgramManager.cs
* ProgramManager_Should.cs

## Mentions @username

Tag users that need to review this code

## Definition of Done

1. The project must be fully documented. This includes the following:
    1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    1. Every class must be documented with purpose, author, and methods.
    1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each.

### CODE REVIEW

**Comment by krysmathis** [comment]
👍

**Comment by kimberly-bird** [comment]
@krysmathis I just added `[Fact]` to the dispose method. Testing is still working for me. Let me know if it doesn't work for you.

**Comment by krysmathis** [comment]
👍

**Comment by Chewieez** [comment]
👍

**Pull request merged**
