### PR TITLE
Gl menu add product to order

### LINKED ISSUE #5: User should be able to add product to customer order
**Given** a customer has been made active in the program
**When** the user selects the option to add a product to the active customer's order
**Then** the user should be prompted with a numbered list of all products
**And** when one is chosen, the product should be added to an order for the active customer

> **Pro tip**: To make it easier to add multiple products, when the user selects a product to add to the customer's order, display the menu of products again. Make sure the last option provides the option to go back to main menu.

```bash
1. Diapers
2. Case of Cracking Cola
3. Bicycle
4. AA Batteries
...
9. Done adding products
```

### PR DESCRIPTION
**Pull request by Chewieez**
## Link to Ticket
Closes #5 ::  User should be able to add product to customer order

## Description of Proposed Changes

- added menu option 6 to main menu to add a product to an active customer's order
- added Case 6 to switch statement for menu in Program.cs
- refactored OrderManagerShould tests to use dynamics ids

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout gl-MenuAddProductToOrder
cd bangazon-cli.Tests
dotnet restore
dotnet test
```
Then 
```sh
cd ..
cd bangazon-cli
dotnet restore
dotnet run
```

1. Add a customer if no customers are currently in your database via menu option 1
1. Select a customer as the active customer via menu option 2
1. Add two or more products via DB Browser SQL insert statements
1. Add a product to shopping cart via menu option 6 and then press enter.
1. Add another product to your shopping cart and then press enter
1. Press the menu option to return to the main menu. 

Open your database in DB Browser and confirm that you have added records to the OrderProduct Table.

## Impacted Areas in Application

List general components of the application that this PR will affect:

* AddProductToCartMenu.cs
* Program.cs

## Mentions @username

Tag users that need to review this code

## Definition of Done

1. The project must be fully documented. This includes the following:
    1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    1. Every class must be documented with purpose, author, and methods.
    1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each.

### CODE REVIEW

**Comment by krysmathis** [comment]
Remove console output of customerId when adding a product to order

**Comment by kimberly-bird** [comment]
👍

**Comment by kimberly-bird** [comment]
👍  x 2 :)

**Comment by krysmathis** [comment]
👍

**Pull request merged**
