### PR TITLE
Gl integrating db into order manager

### PR DESCRIPTION
**Pull request by Chewieez**
## Link to Ticket 
#5 [Link]()

## Description of Proposed Changes

- refactored AddOrder function and GetUnpaidOrder function to use the database
- added code to create a OrderProduct table in database to store relationship of order and product
- added instance of OrderManager to Program.cs to have ability to control the order that tables are created, if they need to be created. 
- added function to add a product to the order product table in database and added test to check if it was added

## Steps to Test

Outline the steps to test

Make sure you are in the root directory of project
```sh
git fetch --all
git checkout gl-integratingDbIntoOrderManager
cd bangazon-cli.Tests
dotnet restore
dotnet test
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* OrderManager.cs
* OrderManagerShould.cs
* database
* Program.cs

## Mentions @username

Tag users that need to review this code

## Definition of Done

1. The project must be fully documented. This includes the following:
    1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    1. Every class must be documented with purpose, author, and methods.
    1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each.

### CODE REVIEW

**Comment by krysmathis** [comment]
Duplicate variable in Program.cs - fix error

**Comment by krysmathis** [comment]
👍

**Comment by kimberly-bird** [comment]
Works! 👍

**Comment by krysmathis** [comment]
👍

**Comment by DreRandaci** [comment]
👍

**Pull request merged**
